### PR TITLE
Add banner to warn about non-prod environments - fixes #1032

### LINKED ISSUE #1032: Add a loud header to staging server so you know it's staging, not production

### PR DESCRIPTION
**Pull request by bengm**
This fixes issue #1032 

If the Rails.env is 'production', the app displays as normal.
If the Rails.env is anything other than 'production', it displays a simple one-line white-on-red banner at the top of the page, with text similar to "You are viewing the STAGING environment". 

__NOTE__: this solution makes two key assumptions:
1) In production, Rails.env == 'production'
2) In staging, Rails.env !== 'production'

### CODE REVIEW

**Comment by john** [comment]
Hi @bengm, thanks so much for the PR. Looks like the build is failing due to the lack of a Devise secret key--which is unexpected, since it's supposed to default to the Rails one if that's not present in the Devise initializer, which you can see in a comment on devise.rb itself. But in any case, if you add this to devise.rg: `config.secret_key = Rails.application.credentials.secret_key_base`, I thin it will make that explicit and hopefully fix the build.

**Comment by bengm** [comment]
[This SO answer](https://stackoverflow.com/questions/51244316/whats-causing-the-lack-of-secret-key-base-on-circleci-with-rails-5-2) (unconfirmed/unvoted) suggests that upgrading devise worked for them (to 4.5.0, this project is currently at 4.4.3). But... the devise version hasn't changed in the gemfile since 3 months ago.

**Comment by bengm** [comment]
The build succeeds when removing any explicit `config.secret_key =...` but upgrading devise to 4.5.0.

**Comment by john** [comment]
Two things:
- Gemfile conflict needs to be resolved after your Devise upgrade (thank you for that), and...
- Staging is running in production mode! Very bad, though somewhat hidden because Heroku overrides database.yml, so it's hitting a different DB. I'm putting together a PR right now to create a proper staging mode, which we should merge before merging this one. This is a great PR if only because it revealed that possibly dangerous misconfiguration :-)

**Comment by john** [comment]
I added the staging env, so approved and merging. Thanks for the specs :-)

**Pull request merged**
